
CREATE DATABASE products;
CREATE DATABASE orders;
CREATE DATABASE users;

GRANT ALL PRIVILEGES ON DATABASE products TO postgres;
GRANT ALL PRIVILEGES ON DATABASE orders TO postgres;
GRANT ALL PRIVILEGES ON DATABASE users TO postgres; 