CREATE DATABASE IF NOT EXISTS products;
CREATE DATABASE IF NOT EXISTS orders;
CREATE DATABASE IF NOT EXISTS users;

GRANT ALL PRIVILEGES ON DATABASE products TO $POSTGRES_USER;
GRANT ALL PRIVILEGES ON DATABASE orders TO $POSTGRES_USER;
GRANT ALL PRIVILEGES ON DATABASE users TO $POSTGRES_USER; 